agnostic_nms: false
amp: true
augment: false
batch: 16
bgr: 0.0
box: 6.5
cache: false
close_mosaic: 0
cls: 0.5
copy_paste: 0.0
cos_lr: false
crop_fraction: 1.0
data: /group/jmearlesgrp/scratch/eranario/AGILE/models/yolo_data.yaml
degrees: 0.0
deterministic: true
dfl: 1.5
dnn: false
dropout: 0.5
dynamic: false
epochs: 50
erasing: 0.4
exist_ok: false
fliplr: 0.5
flipud: 0.0
format: torchscript
fraction: 1.0
half: false
hsv_h: 0.1
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
int8: false
iou: 0.3
keras: false
kobj: 1.0
lr0: 0.01
lrf: 0.01
mask_ratio: 4
max_det: 300
mixup: 0.0
mode: train
model: /group/jmearlesgrp/intermediate_data/eranario/AGILE/yolov10n.pt
momentum: 0.937
mosaic: 0.0
multi_scale: false
name: MAHucF
nbs: 64
nms: false
optimize: false
optimizer: auto
overlap_mask: true
patience: 100
perspective: 0.0
plots: true
pose: 12.0
pretrained: true
profile: false
project: /group/jmearlesgrp/intermediate_data/eranario/AGILE/apple_spain2usa/yolo/1206_agile-80-40-10-5_MAHucF
rect: false
resume: false
retina_masks: false
save: true
save_conf: false
save_crop: false
save_frames: false
save_hybrid: false
save_json: true
save_period: -1
save_txt: false
scale: 0.5
seed: 0
shear: 0.0
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
split: val
stream_buffer: false
task: detect
tracker: botsort.yaml
translate: 0.1
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 4
workspace: 4
